// Generated by gencpp from file home_main_sys/home_std_srv.msg
// DO NOT EDIT!


#ifndef HOME_MAIN_SYS_MESSAGE_HOME_STD_SRV_H
#define HOME_MAIN_SYS_MESSAGE_HOME_STD_SRV_H

#include <ros/service_traits.h>


#include <home_main_sys/home_std_srvRequest.h>
#include <home_main_sys/home_std_srvResponse.h>


namespace home_main_sys
{

struct home_std_srv
{

typedef home_std_srvRequest Request;
typedef home_std_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct home_std_srv
} // namespace home_main_sys


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::home_main_sys::home_std_srv > {
  static const char* value()
  {
    return "545d9745cfdca0f0ffe4b73783ff6bc8";
  }

  static const char* value(const ::home_main_sys::home_std_srv&) { return value(); }
};

template<>
struct DataType< ::home_main_sys::home_std_srv > {
  static const char* value()
  {
    return "home_main_sys/home_std_srv";
  }

  static const char* value(const ::home_main_sys::home_std_srv&) { return value(); }
};


// service_traits::MD5Sum< ::home_main_sys::home_std_srvRequest> should match 
// service_traits::MD5Sum< ::home_main_sys::home_std_srv > 
template<>
struct MD5Sum< ::home_main_sys::home_std_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::home_main_sys::home_std_srv >::value();
  }
  static const char* value(const ::home_main_sys::home_std_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::home_main_sys::home_std_srvRequest> should match 
// service_traits::DataType< ::home_main_sys::home_std_srv > 
template<>
struct DataType< ::home_main_sys::home_std_srvRequest>
{
  static const char* value()
  {
    return DataType< ::home_main_sys::home_std_srv >::value();
  }
  static const char* value(const ::home_main_sys::home_std_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::home_main_sys::home_std_srvResponse> should match 
// service_traits::MD5Sum< ::home_main_sys::home_std_srv > 
template<>
struct MD5Sum< ::home_main_sys::home_std_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::home_main_sys::home_std_srv >::value();
  }
  static const char* value(const ::home_main_sys::home_std_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::home_main_sys::home_std_srvResponse> should match 
// service_traits::DataType< ::home_main_sys::home_std_srv > 
template<>
struct DataType< ::home_main_sys::home_std_srvResponse>
{
  static const char* value()
  {
    return DataType< ::home_main_sys::home_std_srv >::value();
  }
  static const char* value(const ::home_main_sys::home_std_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HOME_MAIN_SYS_MESSAGE_HOME_STD_SRV_H
