"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import, division, print_function
from .defmatrix import *
from numpy._pytesttester import PytestTester

"""Sub-package containing the matrix class and related functions.

"""
test = PytestTester(__name__)
