"""
This type stub file was generated by pyright.
"""

"""rospy exception types"""
class ROSException(Exception):
    """
    Base exception class for ROS clients
    """
    ...


class ROSSerializationException(ROSException):
    """
    Exception for message serialization errors
    """
    ...


class ROSInitException(ROSException):
    """
    Exception for errors initializing ROS state
    """
    ...


class ROSInterruptException(ROSException, KeyboardInterrupt):
    """
    Exception for operations that interrupted, e.g. due to shutdown.

    This is a subclass of both L{ROSException} and KeyboardInterrupt
    so that it can be used in logic tht expects either.
    """
    ...


class ROSTimeMovedBackwardsException(ROSInterruptException):
    """
    Exception if time moved backwards
    """
    def __init__(self, time) -> None:
        ...
    


class ROSInternalException(Exception):
    """
    Base class for exceptions that are internal to the ROS system
    """
    ...


class TransportException(ROSInternalException):
    """
    Base class for transport-related exceptions
    """
    ...


class TransportTerminated(TransportException):
    """
    Internal class for representing broken connections
    """
    ...


class TransportInitError(TransportException):
    """
    Internal exception for representing exceptions that occur
    establishing transports
    """
    ...


