"""
This type stub file was generated by pyright.
"""

class ROSConsoleException(Exception):
    """Base exception class of rosconsole-related errors."""
    ...


class LoggerLevelServiceCaller(object):
    """
    Handles service calls for getting lists of nodes and loggers.

    Also handles sending requests to change logger levels.
    """
    def __init__(self) -> None:
        ...
    
    def get_levels(self):
        ...
    
    def get_loggers(self, node):
        ...
    
    def get_node_names(self):
        """
        Get a list of available services via a ros service call.

        :returns: a list of all nodes that provide the set_logger_level service, ''list(str)''
        """
        ...
    
    def send_logger_change_message(self, node, logger, level):
        """
        Send a logger level change request to 'node'.

        :param node: name of the node to chaange, ''str''
        :param logger: name of the logger to change, ''str''
        :param level: name of the level to change, ''str''
        :returns: True if the response is valid, ''bool''
        :returns: False if the request raises an exception or would not change the state, ''bool''
        """
        ...
    


