"""
This type stub file was generated by pyright.
"""

NAME = 'rosconsole'
def error(status, msg):
    ...

class RosConsoleEcho(object):
    LEVEL_COLOR = ...
    LEVEL_MAX_LENGTH = ...
    def __init__(self, options) -> None:
        ...
    
    @staticmethod
    def get_levels():
        """Get levels sorted by increasing severity."""
        ...
    


def main(argv=...):
    ...

