"""
This type stub file was generated by pyright.
"""

import rosgraph

"""
Internal use: rospy initialization.

This is mainly routines for initializing the master or slave based on
the OS environment.
"""
DEFAULT_NODE_PORT = 0
def start_node(environ, resolved_name, master_uri=..., port=..., tcpros_port=...):
    """
    Load ROS slave node, initialize from environment variables
    @param environ: environment variables
    @type  environ: dict
    @param resolved_name: resolved node name
    @type  resolved_name: str
    @param master_uri: override ROS_MASTER_URI: XMlRPC URI of central ROS server
    @type  master_uri: str
    @param port: override ROS_PORT: port of slave xml-rpc node
    @type  port: int
    @param tcpros_port: override the port of the TCP server
    @type  tcpros_port: int
    @return: node server instance
    @rtype rosgraph.xmlrpc.XmlRpcNode
    @raise ROSInitException: if node has already been started
    """
    ...

class RosStreamHandler(rosgraph.roslogging.RosStreamHandler):
    def __init__(self, colorize=..., stdout=..., stderr=...) -> None:
        ...
    


