"""
This type stub file was generated by pyright.
"""

"""Internal-use Python decorators for parameter validation"""
class ParameterInvalid(Exception):
    """Exception that is raised when a parameter fails validation checks"""
    def __init__(self, message) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


def non_empty(param_name):
    """Validator that checks that parameter is not empty"""
    ...

