#goal definition
float64 plane_min_height
float64 plane_max_height
bool ignore_moveit
---
#result definition
bool success
geometry_msgs/PoseStamped target_pose
float64 x_plane
float64 y_plane
float64 z_plane
float64 width_plane
float64 height_plane
---
#feedback
# -1 => Error, 0..1...2 => ObjectsFoundSoFar
int32 status