"""
This type stub file was generated by pyright.
"""

import sys
import subprocess
import os
import numpy as np
from __future__ import absolute_import, division, print_function
from . import diagnose, f2py2e, f2py_testing
from numpy._pytesttester import PytestTester

"""Fortran to Python Interface Generator.

"""
run_main = f2py2e.run_main
main = f2py2e.main
def compile(source, modulename=..., extra_args=..., verbose=..., source_fn=..., extension=...):
    """
    Build extension module from a Fortran 77 source string with f2py.

    Parameters
    ----------
    source : str or bytes
        Fortran source of module / subroutine to compile

        .. versionchanged:: 1.16.0
           Accept str as well as bytes

    modulename : str, optional
        The name of the compiled python module
    extra_args : str or list, optional
        Additional parameters passed to f2py

        .. versionchanged:: 1.16.0
            A list of args may also be provided.

    verbose : bool, optional
        Print f2py output to screen
    source_fn : str, optional
        Name of the file where the fortran source is written.
        The default is to use a temporary file with the extension
        provided by the `extension` parameter
    extension : {'.f', '.f90'}, optional
        Filename extension if `source_fn` is not provided.
        The extension tells which fortran standard is used.
        The default is `.f`, which implies F77 standard.

        .. versionadded:: 1.11.0

    Returns
    -------
    result : int
        0 on success

    Examples
    --------
    .. include:: compile_session.dat
        :literal:

    """
    ...

test = PytestTester(__name__)
