# Use the existing ROS-NOETIC image
FROM ghcr.io/roborregos/robocup-home:speech

LABEL maintainer="Jose Cisneros <A01283070@itesm.mx>"

# Change Workdir
WORKDIR /catkin_home

# catkin_make
RUN /bin/bash -c '. /opt/ros/noetic/setup.bash;catkin_make'

ENTRYPOINT [ "/bin/bash", "-l", "-c" ]
