"""
This type stub file was generated by pyright.
"""

import sys
import re
from distutils.extension import Extension as old_Extension

"""distutils.extension

Provides the Extension class, used to describe C/C++ extension
modules in setup scripts.

Overridden to support f2py.

"""
if sys.version_info[0] >= 3:
    basestring = str
cxx_ext_re = re.compile(r'.*[.](cpp|cxx|cc)\Z', re.I).match
fortran_pyf_ext_re = re.compile(r'.*[.](f90|f95|f77|for|ftn|f|pyf)\Z', re.I).match
class Extension(old_Extension):
    def __init__(self, name, sources, include_dirs=..., define_macros=..., undef_macros=..., library_dirs=..., libraries=..., runtime_library_dirs=..., extra_objects=..., extra_compile_args=..., extra_link_args=..., export_symbols=..., swig_opts=..., depends=..., language=..., f2py_options=..., module_dirs=..., extra_f77_compile_args=..., extra_f90_compile_args=...) -> None:
        ...
    
    def has_cxx_sources(self):
        ...
    
    def has_f2py_sources(self):
        ...
    


