"""
This type stub file was generated by pyright.
"""

from distutils.core import Distribution

class NumpyDistribution(Distribution):
    def __init__(self, attrs=...) -> None:
        ...
    
    def has_scons_scripts(self):
        ...
    


