"""
This type stub file was generated by pyright.
"""

from distutils.unixccompiler import *

"""
unixccompiler - can handle very long argument lists for ar.

"""
if sys.version_info[0] < 3:
    ...
else:
    ...
def UnixCCompiler__compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts):
    """Compile a single source files with a Unix-style compiler."""
    ...

def UnixCCompiler_create_static_lib(self, objects, output_libname, output_dir=..., debug=..., target_lang=...):
    """
    Build a static library in a separate sub-process.

    Parameters
    ----------
    objects : list or tuple of str
        List of paths to object files used to build the static library.
    output_libname : str
        The library name as an absolute or relative (if `output_dir` is used)
        path.
    output_dir : str, optional
        The path to the output directory. Default is None, in which case
        the ``output_dir`` attribute of the UnixCCompiler instance.
    debug : bool, optional
        This parameter is not used.
    target_lang : str, optional
        This parameter is not used.

    Returns
    -------
    None

    """
    ...

