geometry_msgs/PoseStamped object_pose
string object_name
string[] allow_contact_with
int32 arm # 1 -> Left, 2 -> Right
---
#result definition
# Comes from moveit_msgs/MoveItErrorCodes
int32 error_code
---
#feedback
