"""
This type stub file was generated by pyright.
"""

import math
from __future__ import absolute_import, division, print_function
from .info import __doc__
from numpy.version import version as __version__
from .type_check import *
from .index_tricks import *
from .function_base import *
from .mixins import *
from .nanfunctions import *
from .shape_base import *
from .stride_tricks import *
from .twodim_base import *
from .ufunclike import *
from .histograms import *
from . import scimath as emath
from .polynomial import *
from .utils import *
from .arraysetops import *
from .npyio import *
from .financial import *
from .arrayterator import Arrayterator
from .arraypad import *
from ._version import *
from numpy.core._multiarray_umath import tracemalloc_domain
from numpy._pytesttester import PytestTester

test = PytestTester(__name__)
