from typing import Any

ACCESS_FAST: int
ACCESS_MASK: int
ACCESS_READ: int
ACCESS_RW: int
ACCESS_WRITE: int
ADAPTIVE_THRESH_GAUSSIAN_C: int
ADAPTIVE_THRESH_MEAN_C: int
AGAST_FEATURE_DETECTOR_AGAST_5_8: int
AGAST_FEATURE_DETECTOR_AGAST_7_12D: int
AGAST_FEATURE_DETECTOR_AGAST_7_12S: int
AGAST_FEATURE_DETECTOR_NONMAX_SUPPRESSION: int
AGAST_FEATURE_DETECTOR_OAST_9_16: int
AGAST_FEATURE_DETECTOR_THRESHOLD: int
AKAZE_DESCRIPTOR_KAZE: int
AKAZE_DESCRIPTOR_KAZE_UPRIGHT: int
AKAZE_DESCRIPTOR_MLDB: int
AKAZE_DESCRIPTOR_MLDB_UPRIGHT: int
AgastFeatureDetector_AGAST_5_8: int
AgastFeatureDetector_AGAST_7_12d: int
AgastFeatureDetector_AGAST_7_12s: int
AgastFeatureDetector_NONMAX_SUPPRESSION: int
AgastFeatureDetector_OAST_9_16: int
AgastFeatureDetector_THRESHOLD: int
BORDER_CONSTANT: int
BORDER_DEFAULT: int
BORDER_ISOLATED: int
BORDER_REFLECT: int
BORDER_REFLECT101: int
BORDER_REFLECT_101: int
BORDER_REPLICATE: int
BORDER_TRANSPARENT: int
BORDER_WRAP: int
CALIB_CB_ADAPTIVE_THRESH: int
CALIB_CB_ASYMMETRIC_GRID: int
CALIB_CB_CLUSTERING: int
CALIB_CB_FAST_CHECK: int
CALIB_CB_FILTER_QUADS: int
CALIB_CB_NORMALIZE_IMAGE: int
CALIB_CB_SYMMETRIC_GRID: int
CALIB_FIX_ASPECT_RATIO: int
CALIB_FIX_FOCAL_LENGTH: int
CALIB_FIX_INTRINSIC: int
CALIB_FIX_K1: int
CALIB_FIX_K2: int
CALIB_FIX_K3: int
CALIB_FIX_K4: int
CALIB_FIX_K5: int
CALIB_FIX_K6: int
CALIB_FIX_PRINCIPAL_POINT: int
CALIB_FIX_S1_S2_S3_S4: int
CALIB_FIX_TAUX_TAUY: int
CALIB_RATIONAL_MODEL: int
CALIB_SAME_FOCAL_LENGTH: int
CALIB_THIN_PRISM_MODEL: int
CALIB_TILTED_MODEL: int
CALIB_USE_INTRINSIC_GUESS: int
CALIB_USE_LU: int
CALIB_USE_QR: int
CALIB_ZERO_DISPARITY: int
CALIB_ZERO_TANGENT_DIST: int
CAP_ANDROID: int
CAP_ANY: int
CAP_ARAVIS: int
CAP_AVFOUNDATION: int
CAP_CMU1394: int
CAP_DC1394: int
CAP_DSHOW: int
CAP_FFMPEG: int
CAP_FIREWARE: int
CAP_FIREWIRE: int
CAP_GIGANETIX: int
CAP_GPHOTO2: int
CAP_GSTREAMER: int
CAP_IEEE1394: int
CAP_IMAGES: int
CAP_INTELPERC: int
CAP_INTELPERC_DEPTH_GENERATOR: int
CAP_INTELPERC_DEPTH_MAP: int
CAP_INTELPERC_GENERATORS_MASK: int
CAP_INTELPERC_IMAGE: int
CAP_INTELPERC_IMAGE_GENERATOR: int
CAP_INTELPERC_IR_MAP: int
CAP_INTELPERC_UVDEPTH_MAP: int
CAP_MODE_BGR: int
CAP_MODE_GRAY: int
CAP_MODE_RGB: int
CAP_MODE_YUYV: int
CAP_MSMF: int
CAP_OPENNI: int
CAP_OPENNI2: int
CAP_OPENNI2_ASUS: int
CAP_OPENNI_ASUS: int
CAP_OPENNI_BGR_IMAGE: int
CAP_OPENNI_DEPTH_GENERATOR: int
CAP_OPENNI_DEPTH_GENERATOR_BASELINE: int
CAP_OPENNI_DEPTH_GENERATOR_FOCAL_LENGTH: int
CAP_OPENNI_DEPTH_GENERATOR_PRESENT: int
CAP_OPENNI_DEPTH_GENERATOR_REGISTRATION: int
CAP_OPENNI_DEPTH_GENERATOR_REGISTRATION_ON: int
CAP_OPENNI_DEPTH_MAP: int
CAP_OPENNI_DISPARITY_MAP: int
CAP_OPENNI_DISPARITY_MAP_32F: int
CAP_OPENNI_GENERATORS_MASK: int
CAP_OPENNI_GRAY_IMAGE: int
CAP_OPENNI_IMAGE_GENERATOR: int
CAP_OPENNI_IMAGE_GENERATOR_OUTPUT_MODE: int
CAP_OPENNI_IMAGE_GENERATOR_PRESENT: int
CAP_OPENNI_IR_GENERATOR: int
CAP_OPENNI_IR_GENERATOR_PRESENT: int
CAP_OPENNI_IR_IMAGE: int
CAP_OPENNI_POINT_CLOUD_MAP: int
CAP_OPENNI_QVGA_30HZ: int
CAP_OPENNI_QVGA_60HZ: int
CAP_OPENNI_SXGA_15HZ: int
CAP_OPENNI_SXGA_30HZ: int
CAP_OPENNI_VALID_DEPTH_MASK: int
CAP_OPENNI_VGA_30HZ: int
CAP_PROP_APERTURE: int
CAP_PROP_AUTOFOCUS: int
CAP_PROP_AUTO_EXPOSURE: int
CAP_PROP_BACKLIGHT: int
CAP_PROP_BRIGHTNESS: int
CAP_PROP_BUFFERSIZE: int
CAP_PROP_CONTRAST: int
CAP_PROP_CONVERT_RGB: int
CAP_PROP_DC1394_MAX: int
CAP_PROP_DC1394_MODE_AUTO: int
CAP_PROP_DC1394_MODE_MANUAL: int
CAP_PROP_DC1394_MODE_ONE_PUSH_AUTO: int
CAP_PROP_DC1394_OFF: int
CAP_PROP_EXPOSURE: int
CAP_PROP_EXPOSUREPROGRAM: int
CAP_PROP_FOCUS: int
CAP_PROP_FORMAT: int
CAP_PROP_FOURCC: int
CAP_PROP_FPS: int
CAP_PROP_FRAME_COUNT: int
CAP_PROP_FRAME_HEIGHT: int
CAP_PROP_FRAME_WIDTH: int
CAP_PROP_GAIN: int
CAP_PROP_GAMMA: int
CAP_PROP_GIGA_FRAME_HEIGH_MAX: int
CAP_PROP_GIGA_FRAME_OFFSET_X: int
CAP_PROP_GIGA_FRAME_OFFSET_Y: int
CAP_PROP_GIGA_FRAME_SENS_HEIGH: int
CAP_PROP_GIGA_FRAME_SENS_WIDTH: int
CAP_PROP_GIGA_FRAME_WIDTH_MAX: int
CAP_PROP_GPHOTO2_COLLECT_MSGS: int
CAP_PROP_GPHOTO2_FLUSH_MSGS: int
CAP_PROP_GPHOTO2_PREVIEW: int
CAP_PROP_GPHOTO2_RELOAD_CONFIG: int
CAP_PROP_GPHOTO2_RELOAD_ON_CHANGE: int
CAP_PROP_GPHOTO2_WIDGET_ENUMERATE: int
CAP_PROP_GSTREAMER_QUEUE_LENGTH: int
CAP_PROP_GUID: int
CAP_PROP_HUE: int
CAP_PROP_IMAGES_BASE: int
CAP_PROP_IMAGES_LAST: int
CAP_PROP_INTELPERC_DEPTH_CONFIDENCE_THRESHOLD: int
CAP_PROP_INTELPERC_DEPTH_FOCAL_LENGTH_HORZ: int
CAP_PROP_INTELPERC_DEPTH_FOCAL_LENGTH_VERT: int
CAP_PROP_INTELPERC_DEPTH_LOW_CONFIDENCE_VALUE: int
CAP_PROP_INTELPERC_DEPTH_SATURATION_VALUE: int
CAP_PROP_INTELPERC_PROFILE_COUNT: int
CAP_PROP_INTELPERC_PROFILE_IDX: int
CAP_PROP_IOS_DEVICE_EXPOSURE: int
CAP_PROP_IOS_DEVICE_FLASH: int
CAP_PROP_IOS_DEVICE_FOCUS: int
CAP_PROP_IOS_DEVICE_TORCH: int
CAP_PROP_IOS_DEVICE_WHITEBALANCE: int
CAP_PROP_IRIS: int
CAP_PROP_ISO_SPEED: int
CAP_PROP_MODE: int
CAP_PROP_MONOCHROME: int
CAP_PROP_OPENNI2_MIRROR: int
CAP_PROP_OPENNI2_SYNC: int
CAP_PROP_OPENNI_APPROX_FRAME_SYNC: int
CAP_PROP_OPENNI_BASELINE: int
CAP_PROP_OPENNI_CIRCLE_BUFFER: int
CAP_PROP_OPENNI_FOCAL_LENGTH: int
CAP_PROP_OPENNI_FRAME_MAX_DEPTH: int
CAP_PROP_OPENNI_GENERATOR_PRESENT: int
CAP_PROP_OPENNI_MAX_BUFFER_SIZE: int
CAP_PROP_OPENNI_MAX_TIME_DURATION: int
CAP_PROP_OPENNI_OUTPUT_MODE: int
CAP_PROP_OPENNI_REGISTRATION: int
CAP_PROP_OPENNI_REGISTRATION_ON: int
CAP_PROP_PAN: int
CAP_PROP_POS_AVI_RATIO: int
CAP_PROP_POS_FRAMES: int
CAP_PROP_POS_MSEC: int
CAP_PROP_PVAPI_BINNINGX: int
CAP_PROP_PVAPI_BINNINGY: int
CAP_PROP_PVAPI_DECIMATIONHORIZONTAL: int
CAP_PROP_PVAPI_DECIMATIONVERTICAL: int
CAP_PROP_PVAPI_FRAMESTARTTRIGGERMODE: int
CAP_PROP_PVAPI_MULTICASTIP: int
CAP_PROP_PVAPI_PIXELFORMAT: int
CAP_PROP_RECTIFICATION: int
CAP_PROP_ROLL: int
CAP_PROP_SATURATION: int
CAP_PROP_SETTINGS: int
CAP_PROP_SHARPNESS: int
CAP_PROP_SPEED: int
CAP_PROP_TEMPERATURE: int
CAP_PROP_TILT: int
CAP_PROP_TRIGGER: int
CAP_PROP_TRIGGER_DELAY: int
CAP_PROP_VIEWFINDER: int
CAP_PROP_WHITE_BALANCE_BLUE_U: int
CAP_PROP_WHITE_BALANCE_RED_V: int
CAP_PROP_XI_ACQ_BUFFER_SIZE: int
CAP_PROP_XI_ACQ_BUFFER_SIZE_UNIT: int
CAP_PROP_XI_ACQ_FRAME_BURST_COUNT: int
CAP_PROP_XI_ACQ_TIMING_MODE: int
CAP_PROP_XI_ACQ_TRANSPORT_BUFFER_COMMIT: int
CAP_PROP_XI_ACQ_TRANSPORT_BUFFER_SIZE: int
CAP_PROP_XI_AEAG: int
CAP_PROP_XI_AEAG_LEVEL: int
CAP_PROP_XI_AEAG_ROI_HEIGHT: int
CAP_PROP_XI_AEAG_ROI_OFFSET_X: int
CAP_PROP_XI_AEAG_ROI_OFFSET_Y: int
CAP_PROP_XI_AEAG_ROI_WIDTH: int
CAP_PROP_XI_AE_MAX_LIMIT: int
CAP_PROP_XI_AG_MAX_LIMIT: int
CAP_PROP_XI_APPLY_CMS: int
CAP_PROP_XI_AUTO_BANDWIDTH_CALCULATION: int
CAP_PROP_XI_AUTO_WB: int
CAP_PROP_XI_AVAILABLE_BANDWIDTH: int
CAP_PROP_XI_BINNING_HORIZONTAL: int
CAP_PROP_XI_BINNING_PATTERN: int
CAP_PROP_XI_BINNING_SELECTOR: int
CAP_PROP_XI_BINNING_VERTICAL: int
CAP_PROP_XI_BPC: int
CAP_PROP_XI_BUFFERS_QUEUE_SIZE: int
CAP_PROP_XI_BUFFER_POLICY: int
CAP_PROP_XI_CC_MATRIX_00: int
CAP_PROP_XI_CC_MATRIX_01: int
CAP_PROP_XI_CC_MATRIX_02: int
CAP_PROP_XI_CC_MATRIX_03: int
CAP_PROP_XI_CC_MATRIX_10: int
CAP_PROP_XI_CC_MATRIX_11: int
CAP_PROP_XI_CC_MATRIX_12: int
CAP_PROP_XI_CC_MATRIX_13: int
CAP_PROP_XI_CC_MATRIX_20: int
CAP_PROP_XI_CC_MATRIX_21: int
CAP_PROP_XI_CC_MATRIX_22: int
CAP_PROP_XI_CC_MATRIX_23: int
CAP_PROP_XI_CC_MATRIX_30: int
CAP_PROP_XI_CC_MATRIX_31: int
CAP_PROP_XI_CC_MATRIX_32: int
CAP_PROP_XI_CC_MATRIX_33: int
CAP_PROP_XI_CHIP_TEMP: int
CAP_PROP_XI_CMS: int
CAP_PROP_XI_COLOR_FILTER_ARRAY: int
CAP_PROP_XI_COLUMN_FPN_CORRECTION: int
CAP_PROP_XI_COOLING: int
CAP_PROP_XI_COUNTER_SELECTOR: int
CAP_PROP_XI_COUNTER_VALUE: int
CAP_PROP_XI_DATA_FORMAT: int
CAP_PROP_XI_DEBOUNCE_EN: int
CAP_PROP_XI_DEBOUNCE_POL: int
CAP_PROP_XI_DEBOUNCE_T0: int
CAP_PROP_XI_DEBOUNCE_T1: int
CAP_PROP_XI_DEBUG_LEVEL: int
CAP_PROP_XI_DECIMATION_HORIZONTAL: int
CAP_PROP_XI_DECIMATION_PATTERN: int
CAP_PROP_XI_DECIMATION_SELECTOR: int
CAP_PROP_XI_DECIMATION_VERTICAL: int
CAP_PROP_XI_DEFAULT_CC_MATRIX: int
CAP_PROP_XI_DEVICE_MODEL_ID: int
CAP_PROP_XI_DEVICE_RESET: int
CAP_PROP_XI_DEVICE_SN: int
CAP_PROP_XI_DOWNSAMPLING: int
CAP_PROP_XI_DOWNSAMPLING_TYPE: int
CAP_PROP_XI_EXPOSURE: int
CAP_PROP_XI_EXPOSURE_BURST_COUNT: int
CAP_PROP_XI_EXP_PRIORITY: int
CAP_PROP_XI_FFS_ACCESS_KEY: int
CAP_PROP_XI_FFS_FILE_ID: int
CAP_PROP_XI_FFS_FILE_SIZE: int
CAP_PROP_XI_FRAMERATE: int
CAP_PROP_XI_FREE_FFS_SIZE: int
CAP_PROP_XI_GAIN: int
CAP_PROP_XI_GAIN_SELECTOR: int
CAP_PROP_XI_GAMMAC: int
CAP_PROP_XI_GAMMAY: int
CAP_PROP_XI_GPI_LEVEL: int
CAP_PROP_XI_GPI_MODE: int
CAP_PROP_XI_GPI_SELECTOR: int
CAP_PROP_XI_GPO_MODE: int
CAP_PROP_XI_GPO_SELECTOR: int
CAP_PROP_XI_HDR: int
CAP_PROP_XI_HDR_KNEEPOINT_COUNT: int
CAP_PROP_XI_HDR_T1: int
CAP_PROP_XI_HDR_T2: int
CAP_PROP_XI_HEIGHT: int
CAP_PROP_XI_HOUS_BACK_SIDE_TEMP: int
CAP_PROP_XI_HOUS_TEMP: int
CAP_PROP_XI_HW_REVISION: int
CAP_PROP_XI_IMAGE_BLACK_LEVEL: int
CAP_PROP_XI_IMAGE_DATA_BIT_DEPTH: int
CAP_PROP_XI_IMAGE_DATA_FORMAT: int
CAP_PROP_XI_IMAGE_DATA_FORMAT_RGB32_ALPHA: int
CAP_PROP_XI_IMAGE_IS_COLOR: int
CAP_PROP_XI_IMAGE_PAYLOAD_SIZE: int
CAP_PROP_XI_IS_COOLED: int
CAP_PROP_XI_IS_DEVICE_EXIST: int
CAP_PROP_XI_KNEEPOINT1: int
CAP_PROP_XI_KNEEPOINT2: int
CAP_PROP_XI_LED_MODE: int
CAP_PROP_XI_LED_SELECTOR: int
CAP_PROP_XI_LENS_APERTURE_VALUE: int
CAP_PROP_XI_LENS_FEATURE: int
CAP_PROP_XI_LENS_FEATURE_SELECTOR: int
CAP_PROP_XI_LENS_FOCAL_LENGTH: int
CAP_PROP_XI_LENS_FOCUS_DISTANCE: int
CAP_PROP_XI_LENS_FOCUS_MOVE: int
CAP_PROP_XI_LENS_FOCUS_MOVEMENT_VALUE: int
CAP_PROP_XI_LENS_MODE: int
CAP_PROP_XI_LIMIT_BANDWIDTH: int
CAP_PROP_XI_LUT_EN: int
CAP_PROP_XI_LUT_INDEX: int
CAP_PROP_XI_LUT_VALUE: int
CAP_PROP_XI_MANUAL_WB: int
CAP_PROP_XI_OFFSET_X: int
CAP_PROP_XI_OFFSET_Y: int
CAP_PROP_XI_OUTPUT_DATA_BIT_DEPTH: int
CAP_PROP_XI_OUTPUT_DATA_PACKING: int
CAP_PROP_XI_OUTPUT_DATA_PACKING_TYPE: int
CAP_PROP_XI_RECENT_FRAME: int
CAP_PROP_XI_REGION_MODE: int
CAP_PROP_XI_REGION_SELECTOR: int
CAP_PROP_XI_ROW_FPN_CORRECTION: int
CAP_PROP_XI_SENSOR_BOARD_TEMP: int
CAP_PROP_XI_SENSOR_CLOCK_FREQ_HZ: int
CAP_PROP_XI_SENSOR_CLOCK_FREQ_INDEX: int
CAP_PROP_XI_SENSOR_DATA_BIT_DEPTH: int
CAP_PROP_XI_SENSOR_FEATURE_SELECTOR: int
CAP_PROP_XI_SENSOR_FEATURE_VALUE: int
CAP_PROP_XI_SENSOR_MODE: int
CAP_PROP_XI_SENSOR_OUTPUT_CHANNEL_COUNT: int
CAP_PROP_XI_SENSOR_TAPS: int
CAP_PROP_XI_SHARPNESS: int
CAP_PROP_XI_SHUTTER_TYPE: int
CAP_PROP_XI_TARGET_TEMP: int
CAP_PROP_XI_TEST_PATTERN: int
CAP_PROP_XI_TEST_PATTERN_GENERATOR_SELECTOR: int
CAP_PROP_XI_TIMEOUT: int
CAP_PROP_XI_TRANSPORT_PIXEL_FORMAT: int
CAP_PROP_XI_TRG_DELAY: int
CAP_PROP_XI_TRG_SELECTOR: int
CAP_PROP_XI_TRG_SOFTWARE: int
CAP_PROP_XI_TRG_SOURCE: int
CAP_PROP_XI_TS_RST_MODE: int
CAP_PROP_XI_TS_RST_SOURCE: int
CAP_PROP_XI_USED_FFS_SIZE: int
CAP_PROP_XI_WB_KB: int
CAP_PROP_XI_WB_KG: int
CAP_PROP_XI_WB_KR: int
CAP_PROP_XI_WIDTH: int
CAP_PROP_ZOOM: int
CAP_PVAPI: int
CAP_PVAPI_DECIMATION_2OUTOF16: int
CAP_PVAPI_DECIMATION_2OUTOF4: int
CAP_PVAPI_DECIMATION_2OUTOF8: int
CAP_PVAPI_DECIMATION_OFF: int
CAP_PVAPI_FSTRIGMODE_FIXEDRATE: int
CAP_PVAPI_FSTRIGMODE_FREERUN: int
CAP_PVAPI_FSTRIGMODE_SOFTWARE: int
CAP_PVAPI_FSTRIGMODE_SYNCIN1: int
CAP_PVAPI_FSTRIGMODE_SYNCIN2: int
CAP_PVAPI_PIXELFORMAT_BAYER16: int
CAP_PVAPI_PIXELFORMAT_BAYER8: int
CAP_PVAPI_PIXELFORMAT_BGR24: int
CAP_PVAPI_PIXELFORMAT_BGRA32: int
CAP_PVAPI_PIXELFORMAT_MONO16: int
CAP_PVAPI_PIXELFORMAT_MONO8: int
CAP_PVAPI_PIXELFORMAT_RGB24: int
CAP_PVAPI_PIXELFORMAT_RGBA32: int
CAP_QT: int
CAP_UNICAP: int
CAP_V4L: int
CAP_V4L2: int
CAP_VFW: int
CAP_WINRT: int
CAP_XIAPI: int
CASCADE_DO_CANNY_PRUNING: int
CASCADE_DO_ROUGH_SEARCH: int
CASCADE_FIND_BIGGEST_OBJECT: int
CASCADE_SCALE_IMAGE: int
CCL_DEFAULT: int
CCL_GRANA: int
CCL_WU: int
CC_STAT_AREA: int
CC_STAT_HEIGHT: int
CC_STAT_LEFT: int
CC_STAT_MAX: int
CC_STAT_TOP: int
CC_STAT_WIDTH: int
CHAIN_APPROX_NONE: int
CHAIN_APPROX_SIMPLE: int
CHAIN_APPROX_TC89_KCOS: int
CHAIN_APPROX_TC89_L1: int
CMP_EQ: int
CMP_GE: int
CMP_GT: int
CMP_LE: int
CMP_LT: int
CMP_NE: int
COLORMAP_AUTUMN: int
COLORMAP_BONE: int
COLORMAP_COOL: int
COLORMAP_HOT: int
COLORMAP_HSV: int
COLORMAP_JET: int
COLORMAP_OCEAN: int
COLORMAP_PARULA: int
COLORMAP_PINK: int
COLORMAP_RAINBOW: int
COLORMAP_SPRING: int
COLORMAP_SUMMER: int
COLORMAP_WINTER: int
COLOR_BAYER_BG2BGR: int
COLOR_BAYER_BG2BGR_EA: int
COLOR_BAYER_BG2BGR_VNG: int
COLOR_BAYER_BG2GRAY: int
COLOR_BAYER_BG2RGB: int
COLOR_BAYER_BG2RGB_EA: int
COLOR_BAYER_BG2RGB_VNG: int
COLOR_BAYER_GB2BGR: int
COLOR_BAYER_GB2BGR_EA: int
COLOR_BAYER_GB2BGR_VNG: int
COLOR_BAYER_GB2GRAY: int
COLOR_BAYER_GB2RGB: int
COLOR_BAYER_GB2RGB_EA: int
COLOR_BAYER_GB2RGB_VNG: int
COLOR_BAYER_GR2BGR: int
COLOR_BAYER_GR2BGR_EA: int
COLOR_BAYER_GR2BGR_VNG: int
COLOR_BAYER_GR2GRAY: int
COLOR_BAYER_GR2RGB: int
COLOR_BAYER_GR2RGB_EA: int
COLOR_BAYER_GR2RGB_VNG: int
COLOR_BAYER_RG2BGR: int
COLOR_BAYER_RG2BGR_EA: int
COLOR_BAYER_RG2BGR_VNG: int
COLOR_BAYER_RG2GRAY: int
COLOR_BAYER_RG2RGB: int
COLOR_BAYER_RG2RGB_EA: int
COLOR_BAYER_RG2RGB_VNG: int
COLOR_BGR2BGR555: int
COLOR_BGR2BGR565: int
COLOR_BGR2BGRA: int
COLOR_BGR2GRAY: int
COLOR_BGR2HLS: int
COLOR_BGR2HLS_FULL: int
COLOR_BGR2HSV: int
COLOR_BGR2HSV_FULL: int
COLOR_BGR2LAB: int
COLOR_BGR2LUV: int
COLOR_BGR2Lab: int
COLOR_BGR2Luv: int
COLOR_BGR2RGB: int
COLOR_BGR2RGBA: int
COLOR_BGR2XYZ: int
COLOR_BGR2YCR_CB: int
COLOR_BGR2YCrCb: int
COLOR_BGR2YUV: int
COLOR_BGR2YUV_I420: int
COLOR_BGR2YUV_IYUV: int
COLOR_BGR2YUV_YV12: int
COLOR_BGR5552BGR: int
COLOR_BGR5552BGRA: int
COLOR_BGR5552GRAY: int
COLOR_BGR5552RGB: int
COLOR_BGR5552RGBA: int
COLOR_BGR5652BGR: int
COLOR_BGR5652BGRA: int
COLOR_BGR5652GRAY: int
COLOR_BGR5652RGB: int
COLOR_BGR5652RGBA: int
COLOR_BGRA2BGR: int
COLOR_BGRA2BGR555: int
COLOR_BGRA2BGR565: int
COLOR_BGRA2GRAY: int
COLOR_BGRA2RGB: int
COLOR_BGRA2RGBA: int
COLOR_BGRA2YUV_I420: int
COLOR_BGRA2YUV_IYUV: int
COLOR_BGRA2YUV_YV12: int
COLOR_BayerBG2BGR: int
COLOR_BayerBG2BGR_EA: int
COLOR_BayerBG2BGR_VNG: int
COLOR_BayerBG2GRAY: int
COLOR_BayerBG2RGB: int
COLOR_BayerBG2RGB_EA: int
COLOR_BayerBG2RGB_VNG: int
COLOR_BayerGB2BGR: int
COLOR_BayerGB2BGR_EA: int
COLOR_BayerGB2BGR_VNG: int
COLOR_BayerGB2GRAY: int
COLOR_BayerGB2RGB: int
COLOR_BayerGB2RGB_EA: int
COLOR_BayerGB2RGB_VNG: int
COLOR_BayerGR2BGR: int
COLOR_BayerGR2BGR_EA: int
COLOR_BayerGR2BGR_VNG: int
COLOR_BayerGR2GRAY: int
COLOR_BayerGR2RGB: int
COLOR_BayerGR2RGB_EA: int
COLOR_BayerGR2RGB_VNG: int
COLOR_BayerRG2BGR: int
COLOR_BayerRG2BGR_EA: int
COLOR_BayerRG2BGR_VNG: int
COLOR_BayerRG2GRAY: int
COLOR_BayerRG2RGB: int
COLOR_BayerRG2RGB_EA: int
COLOR_BayerRG2RGB_VNG: int
COLOR_COLORCVT_MAX: int
COLOR_GRAY2BGR: int
COLOR_GRAY2BGR555: int
COLOR_GRAY2BGR565: int
COLOR_GRAY2BGRA: int
COLOR_GRAY2RGB: int
COLOR_GRAY2RGBA: int
COLOR_HLS2BGR: int
COLOR_HLS2BGR_FULL: int
COLOR_HLS2RGB: int
COLOR_HLS2RGB_FULL: int
COLOR_HSV2BGR: int
COLOR_HSV2BGR_FULL: int
COLOR_HSV2RGB: int
COLOR_HSV2RGB_FULL: int
COLOR_LAB2BGR: int
COLOR_LAB2LBGR: int
COLOR_LAB2LRGB: int
COLOR_LAB2RGB: int
COLOR_LBGR2LAB: int
COLOR_LBGR2LUV: int
COLOR_LBGR2Lab: int
COLOR_LBGR2Luv: int
COLOR_LRGB2LAB: int
COLOR_LRGB2LUV: int
COLOR_LRGB2Lab: int
COLOR_LRGB2Luv: int
COLOR_LUV2BGR: int
COLOR_LUV2LBGR: int
COLOR_LUV2LRGB: int
COLOR_LUV2RGB: int
COLOR_Lab2BGR: int
COLOR_Lab2LBGR: int
COLOR_Lab2LRGB: int
COLOR_Lab2RGB: int
COLOR_Luv2BGR: int
COLOR_Luv2LBGR: int
COLOR_Luv2LRGB: int
COLOR_Luv2RGB: int
COLOR_M_RGBA2RGBA: int
COLOR_RGB2BGR: int
COLOR_RGB2BGR555: int
COLOR_RGB2BGR565: int
COLOR_RGB2BGRA: int
COLOR_RGB2GRAY: int
COLOR_RGB2HLS: int
COLOR_RGB2HLS_FULL: int
COLOR_RGB2HSV: int
COLOR_RGB2HSV_FULL: int
COLOR_RGB2LAB: int
COLOR_RGB2LUV: int
COLOR_RGB2Lab: int
COLOR_RGB2Luv: int
COLOR_RGB2RGBA: int
COLOR_RGB2XYZ: int
COLOR_RGB2YCR_CB: int
COLOR_RGB2YCrCb: int
COLOR_RGB2YUV: int
COLOR_RGB2YUV_I420: int
COLOR_RGB2YUV_IYUV: int
COLOR_RGB2YUV_YV12: int
COLOR_RGBA2BGR: int
COLOR_RGBA2BGR555: int
COLOR_RGBA2BGR565: int
COLOR_RGBA2BGRA: int
COLOR_RGBA2GRAY: int
COLOR_RGBA2M_RGBA: int
COLOR_RGBA2RGB: int
COLOR_RGBA2YUV_I420: int
COLOR_RGBA2YUV_IYUV: int
COLOR_RGBA2YUV_YV12: int
COLOR_RGBA2mRGBA: int
COLOR_XYZ2BGR: int
COLOR_XYZ2RGB: int
COLOR_YCR_CB2BGR: int
COLOR_YCR_CB2RGB: int
COLOR_YCrCb2BGR: int
COLOR_YCrCb2RGB: int
COLOR_YUV2BGR: int
COLOR_YUV2BGRA_I420: int
COLOR_YUV2BGRA_IYUV: int
COLOR_YUV2BGRA_NV12: int
COLOR_YUV2BGRA_NV21: int
COLOR_YUV2BGRA_UYNV: int
COLOR_YUV2BGRA_UYVY: int
COLOR_YUV2BGRA_Y422: int
COLOR_YUV2BGRA_YUNV: int
COLOR_YUV2BGRA_YUY2: int
COLOR_YUV2BGRA_YUYV: int
COLOR_YUV2BGRA_YV12: int
COLOR_YUV2BGRA_YVYU: int
COLOR_YUV2BGR_I420: int
COLOR_YUV2BGR_IYUV: int
COLOR_YUV2BGR_NV12: int
COLOR_YUV2BGR_NV21: int
COLOR_YUV2BGR_UYNV: int
COLOR_YUV2BGR_UYVY: int
COLOR_YUV2BGR_Y422: int
COLOR_YUV2BGR_YUNV: int
COLOR_YUV2BGR_YUY2: int
COLOR_YUV2BGR_YUYV: int
COLOR_YUV2BGR_YV12: int
COLOR_YUV2BGR_YVYU: int
COLOR_YUV2GRAY_420: int
COLOR_YUV2GRAY_I420: int
COLOR_YUV2GRAY_IYUV: int
COLOR_YUV2GRAY_NV12: int
COLOR_YUV2GRAY_NV21: int
COLOR_YUV2GRAY_UYNV: int
COLOR_YUV2GRAY_UYVY: int
COLOR_YUV2GRAY_Y422: int
COLOR_YUV2GRAY_YUNV: int
COLOR_YUV2GRAY_YUY2: int
COLOR_YUV2GRAY_YUYV: int
COLOR_YUV2GRAY_YV12: int
COLOR_YUV2GRAY_YVYU: int
COLOR_YUV2RGB: int
COLOR_YUV2RGBA_I420: int
COLOR_YUV2RGBA_IYUV: int
COLOR_YUV2RGBA_NV12: int
COLOR_YUV2RGBA_NV21: int
COLOR_YUV2RGBA_UYNV: int
COLOR_YUV2RGBA_UYVY: int
COLOR_YUV2RGBA_Y422: int
COLOR_YUV2RGBA_YUNV: int
COLOR_YUV2RGBA_YUY2: int
COLOR_YUV2RGBA_YUYV: int
COLOR_YUV2RGBA_YV12: int
COLOR_YUV2RGBA_YVYU: int
COLOR_YUV2RGB_I420: int
COLOR_YUV2RGB_IYUV: int
COLOR_YUV2RGB_NV12: int
COLOR_YUV2RGB_NV21: int
COLOR_YUV2RGB_UYNV: int
COLOR_YUV2RGB_UYVY: int
COLOR_YUV2RGB_Y422: int
COLOR_YUV2RGB_YUNV: int
COLOR_YUV2RGB_YUY2: int
COLOR_YUV2RGB_YUYV: int
COLOR_YUV2RGB_YV12: int
COLOR_YUV2RGB_YVYU: int
COLOR_YUV420P2BGR: int
COLOR_YUV420P2BGRA: int
COLOR_YUV420P2GRAY: int
COLOR_YUV420P2RGB: int
COLOR_YUV420P2RGBA: int
COLOR_YUV420SP2BGR: int
COLOR_YUV420SP2BGRA: int
COLOR_YUV420SP2GRAY: int
COLOR_YUV420SP2RGB: int
COLOR_YUV420SP2RGBA: int
COLOR_YUV420p2BGR: int
COLOR_YUV420p2BGRA: int
COLOR_YUV420p2GRAY: int
COLOR_YUV420p2RGB: int
COLOR_YUV420p2RGBA: int
COLOR_YUV420sp2BGR: int
COLOR_YUV420sp2BGRA: int
COLOR_YUV420sp2GRAY: int
COLOR_YUV420sp2RGB: int
COLOR_YUV420sp2RGBA: int
COLOR_mRGBA2RGBA: int
COVAR_COLS: int
COVAR_NORMAL: int
COVAR_ROWS: int
COVAR_SCALE: int
COVAR_SCRAMBLED: int
COVAR_USE_AVG: int
CV_16S: int
CV_16SC1: int
CV_16SC2: int
CV_16SC3: int
CV_16SC4: int
CV_16U: int
CV_16UC1: int
CV_16UC2: int
CV_16UC3: int
CV_16UC4: int
CV_32F: int
CV_32FC1: int
CV_32FC2: int
CV_32FC3: int
CV_32FC4: int
CV_32S: int
CV_32SC1: int
CV_32SC2: int
CV_32SC3: int
CV_32SC4: int
CV_64F: int
CV_64FC1: int
CV_64FC2: int
CV_64FC3: int
CV_64FC4: int
CV_8S: int
CV_8SC1: int
CV_8SC2: int
CV_8SC3: int
CV_8SC4: int
CV_8U: int
CV_8UC1: int
CV_8UC2: int
CV_8UC3: int
CV_8UC4: int
DCT_INVERSE: int
DCT_ROWS: int
DECOMP_CHOLESKY: int
DECOMP_EIG: int
DECOMP_LU: int
DECOMP_NORMAL: int
DECOMP_QR: int
DECOMP_SVD: int
DESCRIPTOR_MATCHER_BRUTEFORCE: int
DESCRIPTOR_MATCHER_BRUTEFORCE_HAMMING: int
DESCRIPTOR_MATCHER_BRUTEFORCE_HAMMINGLUT: int
DESCRIPTOR_MATCHER_BRUTEFORCE_L1: int
DESCRIPTOR_MATCHER_BRUTEFORCE_SL2: int
DESCRIPTOR_MATCHER_FLANNBASED: int
DFT_COMPLEX_OUTPUT: int
DFT_INVERSE: int
DFT_REAL_OUTPUT: int
DFT_ROWS: int
DFT_SCALE: int
DIST_C: int
DIST_FAIR: int
DIST_HUBER: int
DIST_L1: int
DIST_L12: int
DIST_L2: int
DIST_LABEL_CCOMP: int
DIST_LABEL_PIXEL: int
DIST_MASK_3: int
DIST_MASK_5: int
DIST_MASK_PRECISE: int
DIST_USER: int
DIST_WELSCH: int
DRAW_MATCHES_FLAGS_DEFAULT: int
DRAW_MATCHES_FLAGS_DRAW_OVER_OUTIMG: int
DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS: int
DRAW_MATCHES_FLAGS_NOT_DRAW_SINGLE_POINTS: int
DescriptorMatcher_BRUTEFORCE: int
DescriptorMatcher_BRUTEFORCE_HAMMING: int
DescriptorMatcher_BRUTEFORCE_HAMMINGLUT: int
DescriptorMatcher_BRUTEFORCE_L1: int
DescriptorMatcher_BRUTEFORCE_SL2: int
DescriptorMatcher_FLANNBASED: int
DrawMatchesFlags_DEFAULT: int
DrawMatchesFlags_DRAW_OVER_OUTIMG: int
DrawMatchesFlags_DRAW_RICH_KEYPOINTS: int
DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS: int
EVENT_FLAG_ALTKEY: int
EVENT_FLAG_CTRLKEY: int
EVENT_FLAG_LBUTTON: int
EVENT_FLAG_MBUTTON: int
EVENT_FLAG_RBUTTON: int
EVENT_FLAG_SHIFTKEY: int
EVENT_LBUTTONDBLCLK: int
EVENT_LBUTTONDOWN: int
EVENT_LBUTTONUP: int
EVENT_MBUTTONDBLCLK: int
EVENT_MBUTTONDOWN: int
EVENT_MBUTTONUP: int
EVENT_MOUSEHWHEEL: int
EVENT_MOUSEMOVE: int
EVENT_MOUSEWHEEL: int
EVENT_RBUTTONDBLCLK: int
EVENT_RBUTTONDOWN: int
EVENT_RBUTTONUP: int
FAST_FEATURE_DETECTOR_FAST_N: int
FAST_FEATURE_DETECTOR_NONMAX_SUPPRESSION: int
FAST_FEATURE_DETECTOR_THRESHOLD: int
FAST_FEATURE_DETECTOR_TYPE_5_8: int
FAST_FEATURE_DETECTOR_TYPE_7_12: int
FAST_FEATURE_DETECTOR_TYPE_9_16: int
FILE_NODE_EMPTY: int
FILE_NODE_FLOAT: int
FILE_NODE_FLOW: int
FILE_NODE_INT: int
FILE_NODE_MAP: int
FILE_NODE_NAMED: int
FILE_NODE_NONE: int
FILE_NODE_REAL: int
FILE_NODE_REF: int
FILE_NODE_SEQ: int
FILE_NODE_STR: int
FILE_NODE_STRING: int
FILE_NODE_TYPE_MASK: int
FILE_NODE_USER: int
FILE_STORAGE_APPEND: int
FILE_STORAGE_BASE64: int
FILE_STORAGE_FORMAT_AUTO: int
FILE_STORAGE_FORMAT_JSON: int
FILE_STORAGE_FORMAT_MASK: int
FILE_STORAGE_FORMAT_XML: int
FILE_STORAGE_FORMAT_YAML: int
FILE_STORAGE_INSIDE_MAP: int
FILE_STORAGE_MEMORY: int
FILE_STORAGE_NAME_EXPECTED: int
FILE_STORAGE_READ: int
FILE_STORAGE_UNDEFINED: int
FILE_STORAGE_VALUE_EXPECTED: int
FILE_STORAGE_WRITE: int
FILE_STORAGE_WRITE_BASE64: int
FILLED: int
FLOODFILL_FIXED_RANGE: int
FLOODFILL_MASK_ONLY: int
FM_7POINT: int
FM_8POINT: int
FM_LMEDS: int
FM_RANSAC: int
FONT_HERSHEY_COMPLEX: int
FONT_HERSHEY_COMPLEX_SMALL: int
FONT_HERSHEY_DUPLEX: int
FONT_HERSHEY_PLAIN: int
FONT_HERSHEY_SCRIPT_COMPLEX: int
FONT_HERSHEY_SCRIPT_SIMPLEX: int
FONT_HERSHEY_SIMPLEX: int
FONT_HERSHEY_TRIPLEX: int
FONT_ITALIC: int
FORMATTER_FMT_C: int
FORMATTER_FMT_CSV: int
FORMATTER_FMT_DEFAULT: int
FORMATTER_FMT_MATLAB: int
FORMATTER_FMT_NUMPY: int
FORMATTER_FMT_PYTHON: int
FastFeatureDetector_FAST_N: int
FastFeatureDetector_NONMAX_SUPPRESSION: int
FastFeatureDetector_THRESHOLD: int
FastFeatureDetector_TYPE_5_8: int
FastFeatureDetector_TYPE_7_12: int
FastFeatureDetector_TYPE_9_16: int
FileNode_EMPTY: int
FileNode_FLOAT: int
FileNode_FLOW: int
FileNode_INT: int
FileNode_MAP: int
FileNode_NAMED: int
FileNode_NONE: int
FileNode_REAL: int
FileNode_REF: int
FileNode_SEQ: int
FileNode_STR: int
FileNode_STRING: int
FileNode_TYPE_MASK: int
FileNode_USER: int
FileStorage_APPEND: int
FileStorage_BASE64: int
FileStorage_FORMAT_AUTO: int
FileStorage_FORMAT_JSON: int
FileStorage_FORMAT_MASK: int
FileStorage_FORMAT_XML: int
FileStorage_FORMAT_YAML: int
FileStorage_INSIDE_MAP: int
FileStorage_MEMORY: int
FileStorage_NAME_EXPECTED: int
FileStorage_READ: int
FileStorage_UNDEFINED: int
FileStorage_VALUE_EXPECTED: int
FileStorage_WRITE: int
FileStorage_WRITE_BASE64: int
Formatter_FMT_C: int
Formatter_FMT_CSV: int
Formatter_FMT_DEFAULT: int
Formatter_FMT_MATLAB: int
Formatter_FMT_NUMPY: int
Formatter_FMT_PYTHON: int
GC_BGD: int
GC_EVAL: int
GC_FGD: int
GC_INIT_WITH_MASK: int
GC_INIT_WITH_RECT: int
GC_PR_BGD: int
GC_PR_FGD: int
GEMM_1_T: int
GEMM_2_T: int
GEMM_3_T: int
HAMMING_NORM_TYPE: int
HISTCMP_BHATTACHARYYA: int
HISTCMP_CHISQR: int
HISTCMP_CHISQR_ALT: int
HISTCMP_CORREL: int
HISTCMP_HELLINGER: int
HISTCMP_INTERSECT: int
HISTCMP_KL_DIV: int
HOGDESCRIPTOR_DEFAULT_NLEVELS: int
HOGDESCRIPTOR_L2HYS: int
HOGDescriptor_DEFAULT_NLEVELS: int
HOGDescriptor_L2Hys: int
HOUGH_GRADIENT: int
HOUGH_MULTI_SCALE: int
HOUGH_PROBABILISTIC: int
HOUGH_STANDARD: int
Hamming_normType: int
IMREAD_ANYCOLOR: int
IMREAD_ANYDEPTH: int
IMREAD_COLOR: int
IMREAD_GRAYSCALE: int
IMREAD_IGNORE_ORIENTATION: int
IMREAD_LOAD_GDAL: int
IMREAD_REDUCED_COLOR_2: int
IMREAD_REDUCED_COLOR_4: int
IMREAD_REDUCED_COLOR_8: int
IMREAD_REDUCED_GRAYSCALE_2: int
IMREAD_REDUCED_GRAYSCALE_4: int
IMREAD_REDUCED_GRAYSCALE_8: int
IMREAD_UNCHANGED: int
IMWRITE_JPEG_CHROMA_QUALITY: int
IMWRITE_JPEG_LUMA_QUALITY: int
IMWRITE_JPEG_OPTIMIZE: int
IMWRITE_JPEG_PROGRESSIVE: int
IMWRITE_JPEG_QUALITY: int
IMWRITE_JPEG_RST_INTERVAL: int
IMWRITE_PAM_FORMAT_BLACKANDWHITE: int
IMWRITE_PAM_FORMAT_GRAYSCALE: int
IMWRITE_PAM_FORMAT_GRAYSCALE_ALPHA: int
IMWRITE_PAM_FORMAT_NULL: int
IMWRITE_PAM_FORMAT_RGB: int
IMWRITE_PAM_FORMAT_RGB_ALPHA: int
IMWRITE_PAM_TUPLETYPE: int
IMWRITE_PNG_BILEVEL: int
IMWRITE_PNG_COMPRESSION: int
IMWRITE_PNG_STRATEGY: int
IMWRITE_PNG_STRATEGY_DEFAULT: int
IMWRITE_PNG_STRATEGY_FILTERED: int
IMWRITE_PNG_STRATEGY_FIXED: int
IMWRITE_PNG_STRATEGY_HUFFMAN_ONLY: int
IMWRITE_PNG_STRATEGY_RLE: int
IMWRITE_PXM_BINARY: int
IMWRITE_WEBP_QUALITY: int
INPAINT_NS: int
INPAINT_TELEA: int
INTERSECT_FULL: int
INTERSECT_NONE: int
INTERSECT_PARTIAL: int
INTER_AREA: int
INTER_BITS: int
INTER_BITS2: int
INTER_CUBIC: int
INTER_LANCZOS4: int
INTER_LINEAR: int
INTER_MAX: int
INTER_NEAREST: int
INTER_TAB_SIZE: int
INTER_TAB_SIZE2: int
KAZE_DIFF_CHARBONNIER: int
KAZE_DIFF_PM_G1: int
KAZE_DIFF_PM_G2: int
KAZE_DIFF_WEICKERT: int
KMEANS_PP_CENTERS: int
KMEANS_RANDOM_CENTERS: int
KMEANS_USE_INITIAL_LABELS: int
LDR_SIZE: int
LINE_4: int
LINE_8: int
LINE_AA: int
LMEDS: int
LSD_REFINE_ADV: int
LSD_REFINE_NONE: int
LSD_REFINE_STD: int
MARKER_CROSS: int
MARKER_DIAMOND: int
MARKER_SQUARE: int
MARKER_STAR: int
MARKER_TILTED_CROSS: int
MARKER_TRIANGLE_DOWN: int
MARKER_TRIANGLE_UP: int
MAT_AUTO_STEP: int
MAT_CONTINUOUS_FLAG: int
MAT_DEPTH_MASK: int
MAT_MAGIC_MASK: int
MAT_MAGIC_VAL: int
MAT_SUBMATRIX_FLAG: int
MAT_TYPE_MASK: int
MIXED_CLONE: int
MONOCHROME_TRANSFER: int
MORPH_BLACKHAT: int
MORPH_CLOSE: int
MORPH_CROSS: int
MORPH_DILATE: int
MORPH_ELLIPSE: int
MORPH_ERODE: int
MORPH_GRADIENT: int
MORPH_HITMISS: int
MORPH_OPEN: int
MORPH_RECT: int
MORPH_TOPHAT: int
MOTION_AFFINE: int
MOTION_EUCLIDEAN: int
MOTION_HOMOGRAPHY: int
MOTION_TRANSLATION: int
Mat_AUTO_STEP: int
Mat_CONTINUOUS_FLAG: int
Mat_DEPTH_MASK: int
Mat_MAGIC_MASK: int
Mat_MAGIC_VAL: int
Mat_SUBMATRIX_FLAG: int
Mat_TYPE_MASK: int
NORMAL_CLONE: int
NORMCONV_FILTER: int
NORM_HAMMING: int
NORM_HAMMING2: int
NORM_INF: int
NORM_L1: int
NORM_L2: int
NORM_L2SQR: int
NORM_MINMAX: int
NORM_RELATIVE: int
NORM_TYPE_MASK: int
OPTFLOW_FARNEBACK_GAUSSIAN: int
OPTFLOW_LK_GET_MIN_EIGENVALS: int
OPTFLOW_USE_INITIAL_FLOW: int
ORB_FAST_SCORE: int
ORB_HARRIS_SCORE: int
ORB_K_BYTES: int
ORB_kBytes: int
PARAM_ALGORITHM: int
PARAM_BOOLEAN: int
PARAM_FLOAT: int
PARAM_INT: int
PARAM_MAT: int
PARAM_MAT_VECTOR: int
PARAM_REAL: int
PARAM_STRING: int
PARAM_UCHAR: int
PARAM_UINT64: int
PARAM_UNSIGNED_INT: int
PCA_DATA_AS_COL: int
PCA_DATA_AS_ROW: int
PCA_USE_AVG: int
PROJ_SPHERICAL_EQRECT: int
PROJ_SPHERICAL_ORTHO: int
Param_ALGORITHM: int
Param_BOOLEAN: int
Param_FLOAT: int
Param_INT: int
Param_MAT: int
Param_MAT_VECTOR: int
Param_REAL: int
Param_STRING: int
Param_UCHAR: int
Param_UINT64: int
Param_UNSIGNED_INT: int
QT_CHECKBOX: int
QT_FONT_BLACK: int
QT_FONT_BOLD: int
QT_FONT_DEMIBOLD: int
QT_FONT_LIGHT: int
QT_FONT_NORMAL: int
QT_NEW_BUTTONBAR: int
QT_PUSH_BUTTON: int
QT_RADIOBOX: int
QT_STYLE_ITALIC: int
QT_STYLE_NORMAL: int
QT_STYLE_OBLIQUE: int
RANSAC: int
RECURS_FILTER: int
REDUCE_AVG: int
REDUCE_MAX: int
REDUCE_MIN: int
REDUCE_SUM: int
RETR_CCOMP: int
RETR_EXTERNAL: int
RETR_FLOODFILL: int
RETR_LIST: int
RETR_TREE: int
RHO: int
RNG_NORMAL: int
RNG_UNIFORM: int
ROTATE_180: int
ROTATE_90_CLOCKWISE: int
ROTATE_90_COUNTERCLOCKWISE: int
SOLVELP_MULTI: int
SOLVELP_SINGLE: int
SOLVELP_UNBOUNDED: int
SOLVELP_UNFEASIBLE: int
SOLVEPNP_DLS: int
SOLVEPNP_EPNP: int
SOLVEPNP_ITERATIVE: int
SOLVEPNP_P3P: int
SOLVEPNP_UPNP: int
SORT_ASCENDING: int
SORT_DESCENDING: int
SORT_EVERY_COLUMN: int
SORT_EVERY_ROW: int
SPARSE_MAT_HASH_BIT: int
SPARSE_MAT_HASH_SCALE: int
SPARSE_MAT_MAGIC_VAL: int
SPARSE_MAT_MAX_DIM: int
STEREO_BM_PREFILTER_NORMALIZED_RESPONSE: int
STEREO_BM_PREFILTER_XSOBEL: int
STEREO_MATCHER_DISP_SCALE: int
STEREO_MATCHER_DISP_SHIFT: int
STEREO_SGBM_MODE_HH: int
STEREO_SGBM_MODE_SGBM: int
STEREO_SGBM_MODE_SGBM_3WAY: int
STITCHER_ERR_CAMERA_PARAMS_ADJUST_FAIL: int
STITCHER_ERR_HOMOGRAPHY_EST_FAIL: int
STITCHER_ERR_NEED_MORE_IMGS: int
STITCHER_OK: int
STITCHER_ORIG_RESOL: int
STITCHER_PANORAMA: int
STITCHER_SCANS: int
SUBDIV2D_NEXT_AROUND_DST: int
SUBDIV2D_NEXT_AROUND_LEFT: int
SUBDIV2D_NEXT_AROUND_ORG: int
SUBDIV2D_NEXT_AROUND_RIGHT: int
SUBDIV2D_PREV_AROUND_DST: int
SUBDIV2D_PREV_AROUND_LEFT: int
SUBDIV2D_PREV_AROUND_ORG: int
SUBDIV2D_PREV_AROUND_RIGHT: int
SUBDIV2D_PTLOC_ERROR: int
SUBDIV2D_PTLOC_INSIDE: int
SUBDIV2D_PTLOC_ON_EDGE: int
SUBDIV2D_PTLOC_OUTSIDE_RECT: int
SUBDIV2D_PTLOC_VERTEX: int
SVD_FULL_UV: int
SVD_MODIFY_A: int
SVD_NO_UV: int
SparseMat_HASH_BIT: int
SparseMat_HASH_SCALE: int
SparseMat_MAGIC_VAL: int
SparseMat_MAX_DIM: int
StereoBM_PREFILTER_NORMALIZED_RESPONSE: int
StereoBM_PREFILTER_XSOBEL: int
StereoMatcher_DISP_SCALE: int
StereoMatcher_DISP_SHIFT: int
StereoSGBM_MODE_HH: int
StereoSGBM_MODE_SGBM: int
StereoSGBM_MODE_SGBM_3WAY: int
Stitcher_ERR_CAMERA_PARAMS_ADJUST_FAIL: int
Stitcher_ERR_HOMOGRAPHY_EST_FAIL: int
Stitcher_ERR_NEED_MORE_IMGS: int
Stitcher_OK: int
Stitcher_ORIG_RESOL: int
Stitcher_PANORAMA: int
Stitcher_SCANS: int
Subdiv2D_NEXT_AROUND_DST: int
Subdiv2D_NEXT_AROUND_LEFT: int
Subdiv2D_NEXT_AROUND_ORG: int
Subdiv2D_NEXT_AROUND_RIGHT: int
Subdiv2D_PREV_AROUND_DST: int
Subdiv2D_PREV_AROUND_LEFT: int
Subdiv2D_PREV_AROUND_ORG: int
Subdiv2D_PREV_AROUND_RIGHT: int
Subdiv2D_PTLOC_ERROR: int
Subdiv2D_PTLOC_INSIDE: int
Subdiv2D_PTLOC_ON_EDGE: int
Subdiv2D_PTLOC_OUTSIDE_RECT: int
Subdiv2D_PTLOC_VERTEX: int
TERM_CRITERIA_COUNT: int
TERM_CRITERIA_EPS: int
TERM_CRITERIA_MAX_ITER: int
THRESH_BINARY: int
THRESH_BINARY_INV: int
THRESH_MASK: int
THRESH_OTSU: int
THRESH_TOZERO: int
THRESH_TOZERO_INV: int
THRESH_TRIANGLE: int
THRESH_TRUNC: int
TM_CCOEFF: int
TM_CCOEFF_NORMED: int
TM_CCORR: int
TM_CCORR_NORMED: int
TM_SQDIFF: int
TM_SQDIFF_NORMED: int
TermCriteria_COUNT: int
TermCriteria_EPS: int
TermCriteria_MAX_ITER: int
UMAT_AUTO_STEP: int
UMAT_CONTINUOUS_FLAG: int
UMAT_DATA_COPY_ON_MAP: int
UMAT_DATA_DEVICE_COPY_OBSOLETE: int
UMAT_DATA_DEVICE_MEM_MAPPED: int
UMAT_DATA_HOST_COPY_OBSOLETE: int
UMAT_DATA_TEMP_COPIED_UMAT: int
UMAT_DATA_TEMP_UMAT: int
UMAT_DATA_USER_ALLOCATED: int
UMAT_DEPTH_MASK: int
UMAT_MAGIC_MASK: int
UMAT_MAGIC_VAL: int
UMAT_SUBMATRIX_FLAG: int
UMAT_TYPE_MASK: int
UMatData_COPY_ON_MAP: int
UMatData_DEVICE_COPY_OBSOLETE: int
UMatData_DEVICE_MEM_MAPPED: int
UMatData_HOST_COPY_OBSOLETE: int
UMatData_TEMP_COPIED_UMAT: int
UMatData_TEMP_UMAT: int
UMatData_USER_ALLOCATED: int
UMat_AUTO_STEP: int
UMat_CONTINUOUS_FLAG: int
UMat_DEPTH_MASK: int
UMat_MAGIC_MASK: int
UMat_MAGIC_VAL: int
UMat_SUBMATRIX_FLAG: int
UMat_TYPE_MASK: int
USAGE_ALLOCATE_DEVICE_MEMORY: int
USAGE_ALLOCATE_HOST_MEMORY: int
USAGE_ALLOCATE_SHARED_MEMORY: int
USAGE_DEFAULT: int
VIDEOWRITER_PROP_FRAMEBYTES: int
VIDEOWRITER_PROP_NSTRIPES: int
VIDEOWRITER_PROP_QUALITY: int
WARP_FILL_OUTLIERS: int
WARP_INVERSE_MAP: int
WINDOW_AUTOSIZE: int
WINDOW_FREERATIO: int
WINDOW_FULLSCREEN: int
WINDOW_GUI_EXPANDED: int
WINDOW_GUI_NORMAL: int
WINDOW_KEEPRATIO: int
WINDOW_NORMAL: int
WINDOW_OPENGL: int
WND_PROP_ASPECT_RATIO: int
WND_PROP_AUTOSIZE: int
WND_PROP_FULLSCREEN: int
WND_PROP_OPENGL: int
WND_PROP_VISIBLE: int
_INPUT_ARRAY_CUDA_GPU_MAT: int
_INPUT_ARRAY_CUDA_HOST_MEM: int
_INPUT_ARRAY_EXPR: int
_INPUT_ARRAY_FIXED_SIZE: int
_INPUT_ARRAY_FIXED_TYPE: int
_INPUT_ARRAY_KIND_MASK: int
_INPUT_ARRAY_KIND_SHIFT: int
_INPUT_ARRAY_MAT: int
_INPUT_ARRAY_MATX: int
_INPUT_ARRAY_NONE: int
_INPUT_ARRAY_OPENGL_BUFFER: int
_INPUT_ARRAY_STD_BOOL_VECTOR: int
_INPUT_ARRAY_STD_VECTOR: int
_INPUT_ARRAY_STD_VECTOR_CUDA_GPU_MAT: int
_INPUT_ARRAY_STD_VECTOR_MAT: int
_INPUT_ARRAY_STD_VECTOR_UMAT: int
_INPUT_ARRAY_STD_VECTOR_VECTOR: int
_INPUT_ARRAY_UMAT: int
_InputArray_CUDA_GPU_MAT: int
_InputArray_CUDA_HOST_MEM: int
_InputArray_EXPR: int
_InputArray_FIXED_SIZE: int
_InputArray_FIXED_TYPE: int
_InputArray_KIND_MASK: int
_InputArray_KIND_SHIFT: int
_InputArray_MAT: int
_InputArray_MATX: int
_InputArray_NONE: int
_InputArray_OPENGL_BUFFER: int
_InputArray_STD_BOOL_VECTOR: int
_InputArray_STD_VECTOR: int
_InputArray_STD_VECTOR_CUDA_GPU_MAT: int
_InputArray_STD_VECTOR_MAT: int
_InputArray_STD_VECTOR_UMAT: int
_InputArray_STD_VECTOR_VECTOR: int
_InputArray_UMAT: int
_OUTPUT_ARRAY_DEPTH_MASK_16S: int
_OUTPUT_ARRAY_DEPTH_MASK_16U: int
_OUTPUT_ARRAY_DEPTH_MASK_32F: int
_OUTPUT_ARRAY_DEPTH_MASK_32S: int
_OUTPUT_ARRAY_DEPTH_MASK_64F: int
_OUTPUT_ARRAY_DEPTH_MASK_8S: int
_OUTPUT_ARRAY_DEPTH_MASK_8U: int
_OUTPUT_ARRAY_DEPTH_MASK_ALL: int
_OUTPUT_ARRAY_DEPTH_MASK_ALL_BUT_8S: int
_OUTPUT_ARRAY_DEPTH_MASK_FLT: int
_OutputArray_DEPTH_MASK_16S: int
_OutputArray_DEPTH_MASK_16U: int
_OutputArray_DEPTH_MASK_32F: int
_OutputArray_DEPTH_MASK_32S: int
_OutputArray_DEPTH_MASK_64F: int
_OutputArray_DEPTH_MASK_8S: int
_OutputArray_DEPTH_MASK_8U: int
_OutputArray_DEPTH_MASK_ALL: int
_OutputArray_DEPTH_MASK_ALL_BUT_8S: int
_OutputArray_DEPTH_MASK_FLT: int
__UMAT_USAGE_FLAGS_32BIT: int

def AKAZE_create(*args, **kwargs) -> Any: ...
def AgastFeatureDetector_create(*args, **kwargs) -> Any: ...
def BFMatcher(*args, **kwargs) -> Any: ...
def BFMatcher_create(*args, **kwargs) -> Any: ...
def BOWImgDescriptorExtractor(*args, **kwargs) -> Any: ...
def BOWKMeansTrainer(*args, **kwargs) -> Any: ...
def BRISK_create(*args, **kwargs) -> Any: ...
def CamShift(*args, **kwargs) -> Any: ...
def Canny(*args, **kwargs) -> Any: ...
def CascadeClassifier(*args, **kwargs) -> Any: ...
def CascadeClassifier_convert(*args, **kwargs) -> Any: ...
def DMatch(*args, **kwargs) -> Any: ...
def DescriptorMatcher_create(*args, **kwargs) -> Any: ...
def DualTVL1OpticalFlow_create(*args, **kwargs) -> Any: ...
def FarnebackOpticalFlow_create(*args, **kwargs) -> Any: ...
def FastFeatureDetector_create(*args, **kwargs) -> Any: ...
def FileNode(*args, **kwargs) -> Any: ...
def FileStorage(*args, **kwargs) -> Any: ...
def FlannBasedMatcher(*args, **kwargs) -> Any: ...
def FlannBasedMatcher_create(*args, **kwargs) -> Any: ...
def GFTTDetector_create(*args, **kwargs) -> Any: ...
def GaussianBlur(*args, **kwargs) -> Any: ...
def HOGDescriptor(*args, **kwargs) -> Any: ...
def HOGDescriptor_getDaimlerPeopleDetector(*args, **kwargs) -> Any: ...
def HOGDescriptor_getDefaultPeopleDetector(*args, **kwargs) -> Any: ...
def HoughCircles(*args, **kwargs) -> Any: ...
def HoughLines(*args, **kwargs) -> Any: ...
def HoughLinesP(*args, **kwargs) -> Any: ...
def HuMoments(*args, **kwargs) -> Any: ...
def KAZE_create(*args, **kwargs) -> Any: ...
def KalmanFilter(*args, **kwargs) -> Any: ...
def KeyPoint(*args, **kwargs) -> Any: ...
def KeyPoint_convert(*args, **kwargs) -> Any: ...
def KeyPoint_overlap(*args, **kwargs) -> Any: ...
def LUT(*args, **kwargs) -> Any: ...
def Laplacian(*args, **kwargs) -> Any: ...
def MSER_create(*args, **kwargs) -> Any: ...
def Mahalanobis(*args, **kwargs) -> Any: ...
def ORB_create(*args, **kwargs) -> Any: ...
def PCABackProject(*args, **kwargs) -> Any: ...
def PCACompute(*args, **kwargs) -> Any: ...
def PCAProject(*args, **kwargs) -> Any: ...
def PSNR(*args, **kwargs) -> Any: ...
def RQDecomp3x3(*args, **kwargs) -> Any: ...
def Rodrigues(*args, **kwargs) -> Any: ...
def SVBackSubst(*args, **kwargs) -> Any: ...
def SVDecomp(*args, **kwargs) -> Any: ...
def Scharr(*args, **kwargs) -> Any: ...
def SimpleBlobDetector_Params(*args, **kwargs) -> Any: ...
def SimpleBlobDetector_create(*args, **kwargs) -> Any: ...
def Sobel(*args, **kwargs) -> Any: ...
def SparsePyrLKOpticalFlow_create(*args, **kwargs) -> Any: ...
def StereoBM_create(*args, **kwargs) -> Any: ...
def StereoSGBM_create(*args, **kwargs) -> Any: ...
def Subdiv2D(*args, **kwargs) -> Any: ...
def TickMeter(*args, **kwargs) -> Any: ...
def VideoCapture(*args, **kwargs) -> Any: ...
def VideoWriter(*args, **kwargs) -> Any: ...
def VideoWriter_fourcc(*args, **kwargs) -> Any: ...
def absdiff(*args, **kwargs) -> Any: ...
def accumulate(*args, **kwargs) -> Any: ...
def accumulateProduct(*args, **kwargs) -> Any: ...
def accumulateSquare(*args, **kwargs) -> Any: ...
def accumulateWeighted(*args, **kwargs) -> Any: ...
def adaptiveThreshold(*args, **kwargs) -> Any: ...
def add(*args, **kwargs) -> Any: ...
def addText(*args, **kwargs) -> Any: ...
def addWeighted(*args, **kwargs) -> Any: ...
def applyColorMap(*args, **kwargs) -> Any: ...
def approxPolyDP(*args, **kwargs) -> Any: ...
def arcLength(*args, **kwargs) -> Any: ...
def arrowedLine(*args, **kwargs) -> Any: ...
def batchDistance(*args, **kwargs) -> Any: ...
def bilateralFilter(*args, **kwargs) -> Any: ...
def bitwise_and(*args, **kwargs) -> Any: ...
def bitwise_not(*args, **kwargs) -> Any: ...
def bitwise_or(*args, **kwargs) -> Any: ...
def bitwise_xor(*args, **kwargs) -> Any: ...
def blur(*args, **kwargs) -> Any: ...
def borderInterpolate(*args, **kwargs) -> Any: ...
def boundingRect(*args, **kwargs) -> Any: ...
def boxFilter(*args, **kwargs) -> Any: ...
def boxPoints(*args, **kwargs) -> Any: ...
def buildOpticalFlowPyramid(*args, **kwargs) -> Any: ...
def calcBackProject(*args, **kwargs) -> Any: ...
def calcCovarMatrix(*args, **kwargs) -> Any: ...
def calcHist(*args, **kwargs) -> Any: ...
def calcOpticalFlowFarneback(prev, next, flow, pyr_scale, levels, winsize, iterations, poly_n, poly_sigma, flags) -> flow: ...
def calcOpticalFlowPyrLK(*args, **kwargs) -> Any: ...
def calibrateCamera(*args, **kwargs) -> Any: ...
def calibrateCameraExtended(*args, **kwargs) -> Any: ...
def calibrationMatrixValues(*args, **kwargs) -> Any: ...
def cartToPolar(*args, **kwargs) -> Any: ...
def checkHardwareSupport(*args, **kwargs) -> Any: ...
def checkRange(*args, **kwargs) -> Any: ...
def circle(*args, **kwargs) -> Any: ...
def clipLine(*args, **kwargs) -> Any: ...
def colorChange(*args, **kwargs) -> Any: ...
def compare(*args, **kwargs) -> Any: ...
def compareHist(*args, **kwargs) -> Any: ...
def completeSymm(*args, **kwargs) -> Any: ...
def composeRT(*args, **kwargs) -> Any: ...
def computeCorrespondEpilines(*args, **kwargs) -> Any: ...
def connectedComponents(*args, **kwargs) -> Any: ...
def connectedComponentsWithAlgorithm(*args, **kwargs) -> Any: ...
def connectedComponentsWithStats(*args, **kwargs) -> Any: ...
def connectedComponentsWithStatsWithAlgorithm(*args, **kwargs) -> Any: ...
def contourArea(*args, **kwargs) -> Any: ...
def convertFp16(*args, **kwargs) -> Any: ...
def convertMaps(*args, **kwargs) -> Any: ...
def convertPointsFromHomogeneous(*args, **kwargs) -> Any: ...
def convertPointsToHomogeneous(*args, **kwargs) -> Any: ...
def convertScaleAbs(*args, **kwargs) -> Any: ...
def convexHull(*args, **kwargs) -> Any: ...
def convexityDefects(*args, **kwargs) -> Any: ...
def copyMakeBorder(*args, **kwargs) -> Any: ...
def cornerEigenValsAndVecs(*args, **kwargs) -> Any: ...
def cornerHarris(*args, **kwargs) -> Any: ...
def cornerMinEigenVal(*args, **kwargs) -> Any: ...
def cornerSubPix(image, corners, winSize, zeroZone, criteria) -> corners: ...
def correctMatches(*args, **kwargs) -> Any: ...
def countNonZero(*args, **kwargs) -> Any: ...
def createAffineTransformer(*args, **kwargs) -> Any: ...
def createAlignMTB(*args, **kwargs) -> Any: ...
def createBackgroundSubtractorKNN(*args, **kwargs) -> Any: ...
def createBackgroundSubtractorMOG2(*args, **kwargs) -> Any: ...
def createButton(*args, **kwargs) -> Any: ...
def createCLAHE(*args, **kwargs) -> Any: ...
def createCalibrateDebevec(*args, **kwargs) -> Any: ...
def createCalibrateRobertson(*args, **kwargs) -> Any: ...
def createChiHistogramCostExtractor(*args, **kwargs) -> Any: ...
def createEMDHistogramCostExtractor(*args, **kwargs) -> Any: ...
def createEMDL1HistogramCostExtractor(*args, **kwargs) -> Any: ...
def createHanningWindow(*args, **kwargs) -> Any: ...
def createHausdorffDistanceExtractor(*args, **kwargs) -> Any: ...
def createLineSegmentDetector(*args, **kwargs) -> Any: ...
def createMergeDebevec(*args, **kwargs) -> Any: ...
def createMergeMertens(*args, **kwargs) -> Any: ...
def createMergeRobertson(*args, **kwargs) -> Any: ...
def createNormHistogramCostExtractor(*args, **kwargs) -> Any: ...
def createOptFlow_DualTVL1(*args, **kwargs) -> Any: ...
def createShapeContextDistanceExtractor(*args, **kwargs) -> Any: ...
def createStitcher(*args, **kwargs) -> Any: ...
def createThinPlateSplineShapeTransformer(*args, **kwargs) -> Any: ...
def createTonemap(*args, **kwargs) -> Any: ...
def createTonemapDrago(*args, **kwargs) -> Any: ...
def createTonemapDurand(*args, **kwargs) -> Any: ...
def createTonemapMantiuk(*args, **kwargs) -> Any: ...
def createTonemapReinhard(*args, **kwargs) -> Any: ...
def createTrackbar(trackbarName, windowName, value, count, onChange) -> None: ...
def cubeRoot(*args, **kwargs) -> Any: ...
def cvtColor(*args, **kwargs) -> Any: ...
def dct(*args, **kwargs) -> Any: ...
def decolor(*args, **kwargs) -> Any: ...
def decomposeEssentialMat(*args, **kwargs) -> Any: ...
def decomposeHomographyMat(*args, **kwargs) -> Any: ...
def decomposeProjectionMatrix(*args, **kwargs) -> Any: ...
def demosaicing(*args, **kwargs) -> Any: ...
def denoise_TVL1(*args, **kwargs) -> Any: ...
def destroyAllWindows(*args, **kwargs) -> Any: ...
def destroyWindow(winname) -> None: ...
def detailEnhance(*args, **kwargs) -> Any: ...
def determinant(*args, **kwargs) -> Any: ...
def dft(*args, **kwargs) -> Any: ...
def dilate(*args, **kwargs) -> Any: ...
def displayOverlay(*args, **kwargs) -> Any: ...
def displayStatusBar(*args, **kwargs) -> Any: ...
def distanceTransform(*args, **kwargs) -> Any: ...
def distanceTransformWithLabels(*args, **kwargs) -> Any: ...
def divide(*args, **kwargs) -> Any: ...
def drawChessboardCorners(image, patternSize, corners, patternWasFound) -> image: ...
def drawContours(*args, **kwargs) -> Any: ...
def drawKeypoints(*args, **kwargs) -> Any: ...
def drawMarker(*args, **kwargs) -> Any: ...
def drawMatches(*args, **kwargs) -> Any: ...
def drawMatchesKnn(*args, **kwargs) -> Any: ...
def edgePreservingFilter(*args, **kwargs) -> Any: ...
def eigen(*args, **kwargs) -> Any: ...
def ellipse(*args, **kwargs) -> Any: ...
def ellipse2Poly(center, axes, angle, arcStart, arcEnd, delta) -> pts: ...
def equalizeHist(*args, **kwargs) -> Any: ...
def erode(*args, **kwargs) -> Any: ...
def estimateAffine2D(*args, **kwargs) -> Any: ...
def estimateAffine3D(*args, **kwargs) -> Any: ...
def estimateAffinePartial2D(*args, **kwargs) -> Any: ...
def estimateRigidTransform(*args, **kwargs) -> Any: ...
def exp(*args, **kwargs) -> Any: ...
def extractChannel(*args, **kwargs) -> Any: ...
def fastAtan2(*args, **kwargs) -> Any: ...
def fastNlMeansDenoising(*args, **kwargs) -> Any: ...
def fastNlMeansDenoisingColored(*args, **kwargs) -> Any: ...
def fastNlMeansDenoisingColoredMulti(*args, **kwargs) -> Any: ...
def fastNlMeansDenoisingMulti(*args, **kwargs) -> Any: ...
def fillConvexPoly(*args, **kwargs) -> Any: ...
def fillPoly(*args, **kwargs) -> Any: ...
def filter2D(*args, **kwargs) -> Any: ...
def filterSpeckles(*args, **kwargs) -> Any: ...
def findChessboardCorners(*args, **kwargs) -> Any: ...
def findCirclesGrid(*args, **kwargs) -> Any: ...
def findContours(*args, **kwargs) -> Any: ...
def findEssentialMat(*args, **kwargs) -> Any: ...
def findFundamentalMat(*args, **kwargs) -> Any: ...
def findHomography(*args, **kwargs) -> Any: ...
def findNonZero(*args, **kwargs) -> Any: ...
def findTransformECC(*args, **kwargs) -> Any: ...
def fitEllipse(*args, **kwargs) -> Any: ...
def fitLine(*args, **kwargs) -> Any: ...
def flip(*args, **kwargs) -> Any: ...
def floodFill(*args, **kwargs) -> Any: ...
def gemm(*args, **kwargs) -> Any: ...
def getAffineTransform(*args, **kwargs) -> Any: ...
def getBuildInformation(*args, **kwargs) -> Any: ...
def getCPUTickCount(*args, **kwargs) -> Any: ...
def getDefaultNewCameraMatrix(*args, **kwargs) -> Any: ...
def getDerivKernels(*args, **kwargs) -> Any: ...
def getGaborKernel(*args, **kwargs) -> Any: ...
def getGaussianKernel(*args, **kwargs) -> Any: ...
def getNumThreads(*args, **kwargs) -> Any: ...
def getNumberOfCPUs(*args, **kwargs) -> Any: ...
def getOptimalDFTSize(*args, **kwargs) -> Any: ...
def getOptimalNewCameraMatrix(*args, **kwargs) -> Any: ...
def getPerspectiveTransform(*args, **kwargs) -> Any: ...
def getRectSubPix(*args, **kwargs) -> Any: ...
def getRotationMatrix2D(*args, **kwargs) -> Any: ...
def getStructuringElement(*args, **kwargs) -> Any: ...
def getTextSize(*args, **kwargs) -> Any: ...
def getThreadNum(*args, **kwargs) -> Any: ...
def getTickCount(*args, **kwargs) -> Any: ...
def getTickFrequency(*args, **kwargs) -> Any: ...
def getTrackbarPos(*args, **kwargs) -> Any: ...
def getValidDisparityROI(*args, **kwargs) -> Any: ...
def getWindowProperty(*args, **kwargs) -> Any: ...
def goodFeaturesToTrack(*args, **kwargs) -> Any: ...
def grabCut(*args, **kwargs) -> Any: ...
def groupRectangles(*args, **kwargs) -> Any: ...
def haveOpenVX(*args, **kwargs) -> Any: ...
def hconcat(*args, **kwargs) -> Any: ...
def idct(*args, **kwargs) -> Any: ...
def idft(*args, **kwargs) -> Any: ...
def illuminationChange(*args, **kwargs) -> Any: ...
def imdecode(*args, **kwargs) -> Any: ...
def imencode(*args, **kwargs) -> Any: ...
def imread(*args, **kwargs) -> Any: ...
def imreadmulti(*args, **kwargs) -> Any: ...
def imshow(winname, mat) -> None: ...
def imwrite(*args, **kwargs) -> Any: ...
def inRange(*args, **kwargs) -> Any: ...
def initCameraMatrix2D(*args, **kwargs) -> Any: ...
def initUndistortRectifyMap(*args, **kwargs) -> Any: ...
def initWideAngleProjMap(*args, **kwargs) -> Any: ...
def inpaint(*args, **kwargs) -> Any: ...
def insertChannel(src, dst, coi) -> dst: ...
def integral(*args, **kwargs) -> Any: ...
def integral2(*args, **kwargs) -> Any: ...
def integral3(*args, **kwargs) -> Any: ...
def intersectConvexConvex(*args, **kwargs) -> Any: ...
def invert(*args, **kwargs) -> Any: ...
def invertAffineTransform(*args, **kwargs) -> Any: ...
def isContourConvex(*args, **kwargs) -> Any: ...
def kmeans(*args, **kwargs) -> Any: ...
def line(*args, **kwargs) -> Any: ...
def linearPolar(*args, **kwargs) -> Any: ...
def log(*args, **kwargs) -> Any: ...
def logPolar(*args, **kwargs) -> Any: ...
def magnitude(*args, **kwargs) -> Any: ...
def matMulDeriv(*args, **kwargs) -> Any: ...
def matchShapes(*args, **kwargs) -> Any: ...
def matchTemplate(*args, **kwargs) -> Any: ...
def max(*args, **kwargs) -> Any: ...
def mean(*args, **kwargs) -> Any: ...
def meanShift(*args, **kwargs) -> Any: ...
def meanStdDev(*args, **kwargs) -> Any: ...
def medianBlur(*args, **kwargs) -> Any: ...
def merge(*args, **kwargs) -> Any: ...
def min(*args, **kwargs) -> Any: ...
def minAreaRect(*args, **kwargs) -> Any: ...
def minEnclosingCircle(*args, **kwargs) -> Any: ...
def minEnclosingTriangle(*args, **kwargs) -> Any: ...
def minMaxLoc(*args, **kwargs) -> Any: ...
def mixChannels(src, dst, fromTo) -> dst: ...
def moments(*args, **kwargs) -> Any: ...
def morphologyEx(*args, **kwargs) -> Any: ...
def moveWindow(winname, x, y) -> None: ...
def mulSpectrums(*args, **kwargs) -> Any: ...
def mulTransposed(*args, **kwargs) -> Any: ...
def multiply(*args, **kwargs) -> Any: ...
def namedWindow(*args, **kwargs) -> Any: ...
def norm(*args, **kwargs) -> Any: ...
def normalize(*args, **kwargs) -> Any: ...
def patchNaNs(*args, **kwargs) -> Any: ...
def pencilSketch(*args, **kwargs) -> Any: ...
def perspectiveTransform(*args, **kwargs) -> Any: ...
def phase(*args, **kwargs) -> Any: ...
def phaseCorrelate(*args, **kwargs) -> Any: ...
def pointPolygonTest(*args, **kwargs) -> Any: ...
def polarToCart(*args, **kwargs) -> Any: ...
def polylines(*args, **kwargs) -> Any: ...
def pow(*args, **kwargs) -> Any: ...
def preCornerDetect(*args, **kwargs) -> Any: ...
def projectPoints(*args, **kwargs) -> Any: ...
def putText(*args, **kwargs) -> Any: ...
def pyrDown(*args, **kwargs) -> Any: ...
def pyrMeanShiftFiltering(*args, **kwargs) -> Any: ...
def pyrUp(*args, **kwargs) -> Any: ...
def randShuffle(*args, **kwargs) -> Any: ...
def randn(dst, mean, stddev) -> dst: ...
def randu(dst, low, high) -> dst: ...
def recoverPose(*args, **kwargs) -> Any: ...
def rectangle(*args, **kwargs) -> Any: ...
def rectify3Collinear(*args, **kwargs) -> Any: ...
def reduce(*args, **kwargs) -> Any: ...
def remap(*args, **kwargs) -> Any: ...
def repeat(*args, **kwargs) -> Any: ...
def reprojectImageTo3D(*args, **kwargs) -> Any: ...
def resize(*args, **kwargs) -> Any: ...
def resizeWindow(winname, width, height) -> None: ...
def rotate(*args, **kwargs) -> Any: ...
def rotatedRectangleIntersection(*args, **kwargs) -> Any: ...
def sampsonDistance(*args, **kwargs) -> Any: ...
def scaleAdd(*args, **kwargs) -> Any: ...
def seamlessClone(*args, **kwargs) -> Any: ...
def sepFilter2D(*args, **kwargs) -> Any: ...
def setIdentity(*args, **kwargs) -> Any: ...
def setMouseCallback(*args, **kwargs) -> Any: ...
def setNumThreads(nthreads) -> None: ...
def setRNGSeed(seed) -> None: ...
def setTrackbarMax(trackbarname, winname, maxval) -> None: ...
def setTrackbarMin(trackbarname, winname, minval) -> None: ...
def setTrackbarPos(trackbarname, winname, pos) -> None: ...
def setUseOpenVX(flag) -> None: ...
def setUseOptimized(onoff) -> None: ...
def setWindowProperty(winname, prop_id, prop_value) -> None: ...
def setWindowTitle(winname, title) -> None: ...
def solve(*args, **kwargs) -> Any: ...
def solveCubic(*args, **kwargs) -> Any: ...
def solveLP(*args, **kwargs) -> Any: ...
def solvePnP(*args, **kwargs) -> Any: ...
def solvePnPRansac(*args, **kwargs) -> Any: ...
def solvePoly(*args, **kwargs) -> Any: ...
def sort(*args, **kwargs) -> Any: ...
def sortIdx(*args, **kwargs) -> Any: ...
def spatialGradient(*args, **kwargs) -> Any: ...
def split(*args, **kwargs) -> Any: ...
def sqrBoxFilter(*args, **kwargs) -> Any: ...
def sqrt(*args, **kwargs) -> Any: ...
def startWindowThread(*args, **kwargs) -> Any: ...
def stereoCalibrate(*args, **kwargs) -> Any: ...
def stereoRectify(*args, **kwargs) -> Any: ...
def stereoRectifyUncalibrated(*args, **kwargs) -> Any: ...
def stylization(*args, **kwargs) -> Any: ...
def subtract(*args, **kwargs) -> Any: ...
def sumElems(*args, **kwargs) -> Any: ...
def textureFlattening(*args, **kwargs) -> Any: ...
def threshold(*args, **kwargs) -> Any: ...
def trace(*args, **kwargs) -> Any: ...
def transform(*args, **kwargs) -> Any: ...
def transpose(*args, **kwargs) -> Any: ...
def triangulatePoints(*args, **kwargs) -> Any: ...
def undistort(*args, **kwargs) -> Any: ...
def undistortPoints(*args, **kwargs) -> Any: ...
def useOpenVX(*args, **kwargs) -> Any: ...
def useOptimized(*args, **kwargs) -> Any: ...
def validateDisparity(*args, **kwargs) -> Any: ...
def vconcat(*args, **kwargs) -> Any: ...
def waitKey(*args, **kwargs) -> Any: ...
def waitKeyEx(*args, **kwargs) -> Any: ...
def warpAffine(*args, **kwargs) -> Any: ...
def warpPerspective(*args, **kwargs) -> Any: ...
def watershed(image, markers) -> markers: ...

class UMat:
    def __init__(self, *args, **kwargs) -> None: ...
    def get(self, *args, **kwargs) -> Any: ...

class error(Exception): ...
