"""
This type stub file was generated by pyright.
"""

import pytest

"""
Pytest configuration and fixtures for the Numpy test suite.
"""
_old_fpu_mode = None
_collect_results = {  }
def pytest_configure(config):
    ...

@pytest.hookimpl()
def pytest_itemcollected(item):
    """
    Check FPU precision mode was not changed during test collection.

    The clumsy way we do it here is mainly necessary because numpy
    still uses yield tests, which can execute code at test collection
    time.
    """
    ...

@pytest.fixture(scope="function", autouse=True)
def check_fpu_mode(request):
    """
    Check FPU precision mode was not changed during the test.
    """
    ...

@pytest.fixture(autouse=True)
def add_np(doctest_namespace):
    ...

