"""
This type stub file was generated by pyright.
"""

import sys
from numpy.compat import unicode

"""
Due to compatibility, numpy has a very large number of different naming
conventions for the scalar types (those subclassing from `numpy.generic`).
This file produces a convoluted set of dictionaries mapping names to types,
and sometimes other mappings too.

.. data:: allTypes
    A dictionary of names to types that will be exposed as attributes through
    ``np.core.numerictypes.*``

.. data:: sctypeDict
    Similar to `allTypes`, but maps a broader set of aliases to their types.

.. data:: sctypeNA
    NumArray-compatible names for the scalar types. Contains not only
    ``name: type`` mappings, but ``char: name`` mappings too.

    .. deprecated:: 1.16

.. data:: sctypes
    A dictionary keyed by a "type group" string, providing a list of types
    under that group.

"""
sctypeDict = {  }
class TypeNADict(dict):
    def __getitem__(self, key):
        ...
    
    def get(self, key, default=...):
        ...
    


sctypeNA = TypeNADict()
allTypes = {  }
_abstract_types = {  }
_concrete_typeinfo = {  }
_concrete_types = v.type for (k, v) in _concrete_typeinfo.items()
def bitname(obj):
    """Return a bit-width name for a given type object"""
    ...

_int_ctypes = ['long', 'longlong', 'int', 'short', 'byte']
_uint_ctypes = list('u' + t for t in _int_ctypes)
void = allTypes['void']
sctypes = { 'int': [],'uint': [],'float': [],'complex': [],'others': [bool, object, bytes, unicode, void] }
_toadd = ['int', 'float', 'complex', 'bool', 'object']
if sys.version_info[0] >= 3:
    ...
else:
    ...
