"""
This type stub file was generated by pyright.
"""

from os.path import dirname

"""Simple script to compute the api hash of the current API.

The API has is defined by numpy_api_order and ufunc_api_order.

"""
if __name__ == '__main__':
    curdir = dirname(__file__)
