# ----------------------------------------------------------------------
#  Rasa Commands
# ----------------------------------------------------------------------

#: Train and Create model
rasa.train:
	@rasa train
#: Start action server.
rasa.run:
	@rasa run actions & rasa shell
	