name: catkin

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v1
    - uses: betwo/github-setup-catkin@v1.1.1
      with:
        ros-version: 'melodic'
        workspace: '$GITHUB_WORKSPACE/catkin_home'
    - run: |
        cd $GITHUB_WORKSPACE/catkin_home
        catkin_make_isolated
    - run: |
        echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
        cd $GITHUB_WORKSPACE/catkin_home
        catkin_make_isolated --catkin-make-args run_tests
        chmod +x ./check_test_result.sh
        ./check_test_result.sh
        echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
    env:
      QT_QPA_PLATFORM: offscreen
