"""
This type stub file was generated by pyright.
"""

"""This module implements additional tests ala autoconf which can be useful.

"""
def check_inline(cmd):
    """Return the inline identifier (may be empty)."""
    ...

def check_restrict(cmd):
    """Return the restrict identifier (may be empty)."""
    ...

def check_compiler_gcc4(cmd):
    """Return True if the C compiler is GCC 4.x."""
    ...

def check_gcc_function_attribute(cmd, attribute, name):
    """Return True if the given function attribute is supported."""
    ...

def check_gcc_variable_attribute(cmd, attribute):
    """Return True if the given variable attribute is supported."""
    ...

