"""
This type stub file was generated by pyright.
"""

import sys
from setuptools.command.bdist_rpm import bdist_rpm as old_bdist_rpm
from distutils.command.bdist_rpm import bdist_rpm as old_bdist_rpm

if 'setuptools' in sys.modules:
    ...
else:
    ...
class bdist_rpm(old_bdist_rpm):
    ...


